/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#75777d",
        "surface-container-highest": "#e0e3e5",
        "on-primary-container": "#77849c",
        "tertiary-fixed": "#acedff",
        "primary-fixed-dim": "#bac7e1",
        "surface-tint": "#525f75",
        "secondary-fixed": "#cce5ff",
        "primary": "#000000",
        "inverse-surface": "#2d3133",
        "surface-container": "#eceef0",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed": "#001d31",
        "on-surface-variant": "#44474c",
        "on-secondary-container": "#00476e",
        "surface-bright": "#f7f9fb",
        "error": "#ba1a1a",
        "secondary-container": "#5bb8fe",
        "primary-fixed": "#d6e3fe",
        "surface-container-low": "#f2f4f6",
        "secondary": "#006398",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#3a475c",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#004e5c",
        "surface-variant": "#e0e3e5",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "inverse-primary": "#bac7e1",
        "tertiary": "#000000",
        "on-tertiary-container": "#0090a9",
        "secondary-fixed-dim": "#93ccff",
        "on-primary-fixed": "#0e1c2f",
        "surface-dim": "#d8dadc",
        "primary-container": "#0e1c2f",
        "on-error": "#ffffff",
        "tertiary-container": "#001f26",
        "surface": "#f7f9fb",
        "on-surface": "#191c1e",
        "on-tertiary-fixed": "#001f26",
        "tertiary-fixed-dim": "#4cd7f6",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#c5c6cd",
        "background": "#f7f9fb",
        "on-secondary-fixed-variant": "#004b73"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "gutter-desktop": "1.5rem",
        "space-lg": "1.5rem",
        "margin-desktop": "2rem",
        "gutter": "1rem",
        "space-md": "1rem",
        "margin": "1rem"
      },
      fontFamily: {
        "data-display": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "data-display": ["18px", { lineHeight: "24px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-code": ["13px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}
